name: Deploy to Vercel (Personal Project)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      # 1️⃣ Clonar el repo
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Ejecutar tests
      - name: Run tests
        run: npm test

      # 5️⃣ Desplegar directamente a Vercel (producción)
      - name: Deploy to Vercel (production)
        run: npx vercel deploy --prod --token $VERCEL_TOKEN --confirm

